#!/bin/bash

wget --no-check-certificate https://o.scdn.co/thumb/`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 2 "artUrl"|egrep -v "album"|egrep -v "array"|cut -b 44-|cut -d '"' -f 1|egrep -v ^$ | awk -F"/" '{print $NF}'` -O ~/.conky/.cache/album.png
